---
title: "Problem Set 1"
output:
  pdf_document: default
  html_document: default
---

# 1) Public Opinion in the US

We will be using public opinion data from 2019 from the Pew Research Center to conduct some basic analyses in R. The data is called `publicopinionUS.dta`. Remember that this is a Stata file when trying to load it into R. 

--------------------------------------------------------------------------------
 Name                 Description
 -------------------- ----------------------------------------------------------
 `state`               State
 
 `q2`                 Do you approve or disapprove of the way Donald Trump is handling his job as President?
 
 `q73`                On balance, do you think having an increasing number of people of many different races, ethnic groups and nationalities in the United States makes this country a better place to live, a worse place to live, or doesn’t make much difference either way?
 
 `smok1`              Have you smoked at least 100 cigarettes in your entire life
 
 `pvote16a`             In the 2016 presidential election between Donald Trump and Hillary Clinton, did things come up that kept you from voting, or did you happen to vote?
 
 `partyln`        As of today do you lean more to the Republican Party or more to the Democratic Party?
 
--------------------------------------------------------------------------------

## Question 1.1
Load the data into R and check the dimensions of the data. How many observations are there? What is the name of the variables?

```{r}
library(foreign)
# set working directory
d <- read.dta("publicopinionUS.dta")
dim(d)
names(d)
```

## Question 1.2
Generate a binary indicator of support for Donald Trump by using the question "do you approve or disapprove of the way Donald Trump is handling his job as President?" (**q2**). Use this binary indicator to show how many respondents approve how the president is doing his job. 

## Question 1.3
What are the states with the highest and lowest support for Donald Trump?

## Question 1.4 
What is the proportion of republicans that approve Donald Trump?

## Question 1.5
What is the proportion of democrats that approve Donald Trump?

## Question 1.6
What is the state with the highest number of respondents that are both democrats and Trump supporters?

## Question 1.7
Generate a new binary indicator called "support for diversity" using the following question from the survey: "on balance, do you think having an increasing number of people of many different races, ethnic groups and nationalities in the United States makes this country a better place to live, a worse place to live, or doesn’t make much difference either way?"  (**q73**). Answering a better place to live is considered support for diversity. How many people support diversity? What is the mean for support of diversity? 

## Question 1.8.
What is the proportion of Trump supporters that approve diversity? 

## Question 1.9
What are the states with the highest and lowest support for diversity?

## Question 1.10
Generate two binary indicators. One for states located in the midwest (North Dakota, South Dakota, Nebraska, Minnesota, Iowa, Missouri, Wisconsin, Illinois, Kansas, Michigan, Indiana, and Ohio). Other for states located in the south (Alabama, Kentucky, Mississippi,Tennessee,Arkansas, Louisiana, Oklahoma, and Texas). What is the proportion of respondents from the midwest and from the south?

## Question 1.11
What is the proportion of respondents that support Trump in the midwest and in the south?

## Question 1.12
Generate a binary indicator for people that do NOT live in the south and that are democracts? What is the proportion of Trump supporters among that group?

## Question 1.13
Generate two new datasets: one with respondents from the midwest and another with respondents from the south.

## Question 1.14
Generate a binary indicator of having smoked more than 100 cigarettes in your life (**smok1**). Respondents that answered "Yes" are the ones that smokes. Use the binary indicators for support for Trump, support for diversity, and smoking to answer the following questions: What is the average approval of Trump among people that smoke and support diversity? What is the average approval of the Trump among people that smoke and do not support diversity? What is the average approval of Trump among people that do not smoke and support diversity? What is the average approval of Trump among people that do not smoke and do not support diversity?

## Question 1.15
Generate a binary indicator to identify the people that voted in the last election (**pvote16a**). People that answered "voted" are the ones that participated in that election. Check if is true or false that people that voted in the last election are more likely to smoke than people that did not vote.

## Question 1.16
Is it true or false that people from Indiana were more likely to vote than people from Texas? 

## Question 1.17
Run a regression using support for Trump as the dependent variable and support for diversity as the independent variable  (binary indicators). Interpret the results (constant, coefficients, and p-values). Compute and interpret the confidence intervals. 

## Question 1.18
Run a regression using support for Trump as the dependent variable and smoking as the independent variable (binary indicators). Interpret the results (constant, coefficients, and p-values). Compute and interpret the confidence intervals. 

## Question 1.19
Run a regression using support for Trump as the dependent variable and partisanship as the independent variable (nominal variable). Interpret the results (constant, coefficients, and p-values). Compute and interpret the confidence intervals.

## Question 1.20
Generate a scatterplot for diversity and smoking. Interpret the figure. 


